package com.example.todo.data;

import com.example.todo.model.Expense;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class ExpenseData {
    // Make the list non-final so we can add to it
    private static List<Expense> expenses = new ArrayList<>();

    // Keep the original list for resetting or default data
    private static final List<Expense> defaultExpenses = Arrays.asList(
            new Expense(1L, 50.00, "USD", "Food", "Lunch with colleagues", "2025-10-28"),
            new Expense(2L, 25.50, "USD", "Transport", "Taxi to office", "2025-10-28")



    );

    // Categories for the dropdown
    private static final String[] categories = {"Food", "Transport", "Shopping", "Snacks", "Bills", "Travel", "Entertainment", "Other"};

    static {
        // Initialize with default data
        expenses.addAll(defaultExpenses);
    }

    public static List<Expense> getExpenses() {
        return expenses;
    }

    public static String[] getCategories() {
        return categories;
    }

    public static Expense findExpenseById(long id) {
        for (Expense expense : expenses) {
            if (expense.getId() == id) {
                return expense;
            }
        }
        return null;
    }

    // --- NEW METHOD TO ADD AN EXPENSE ---
    public static void addExpense(Expense expense) {
        // In a real app, the ID would be auto-generated by a database.
        // Here, we generate a simple unique ID based on the current time.
        long newId = System.currentTimeMillis();
        Expense newExpenseWithId = new Expense(
                newId,
                expense.getAmount(),
                expense.getCurrency(),
                expense.getCategory(),
                expense.getRemark(),
                expense.getCreatedDate()
        );
        expenses.add(0, newExpenseWithId); // Add to the top of the list
    }
}
